import type { SubmittedListing } from "./submission-types";

export const SEED_IDS = new Set(["L-001", "L-002", "L-003", "L-A01", "L-A02"]);

const SEED_SUBMISSIONS: SubmittedListing[] = [
  {
    id: "L-001",
    title: "Sunset Desert Camp",
    description: "Desert camp experience with traditional hospitality.",
    hostId: "seed-host-1",
    hostName: "Khalid Al Mazrouei",
    status: "pending",
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    country: "India",
    state: "Rajasthan",
    district: "Jaisalmer",
    parentCategory: "Stays",
    category: "Camping & Glamping",
    subcategory: "Desert Camp",
    type: "farmstay",
    city: "Jaisalmer",
    customFilters: [],
    advancedFilters: [],
    photoUrls: [],
    photoCount: 0,
  },
  {
    id: "L-002",
    title: "Oasis Heritage Home",
    description: "Heritage homestay in Al Ain.",
    hostId: "seed-host-2",
    hostName: "Mariam Hassan",
    status: "pending",
    submittedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    country: "India",
    state: "Kerala",
    district: "Wayanad",
    parentCategory: "Stays",
    category: "Homestays",
    subcategory: "Heritage Home",
    type: "homestay",
    city: "Wayanad",
    customFilters: [],
    advancedFilters: [],
    photoUrls: [],
    photoCount: 0,
    flaggedForReview: true,
  },
  {
    id: "L-003",
    title: "Mountain BBQ Experience",
    description: "Outdoor BBQ experience in Hatta.",
    hostId: "seed-host-3",
    hostName: "Omar Farid",
    status: "pending",
    submittedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    country: "India",
    state: "Himachal Pradesh",
    district: "Kullu",
    parentCategory: "Experiences",
    category: "BBQ Experience",
    subcategory: "BBQ Experience",
    type: "experience",
    city: "Kullu",
    customFilters: [],
    advancedFilters: [],
    photoUrls: [],
    photoCount: 0,
  },
];

const SEED_ACTIVE: SubmittedListing[] = [
  {
    id: "L-A01",
    title: "Green Valley Farmhouse",
    description: "Luxury farmhouse retreat surrounded by palm groves in Al Ain.",
    hostId: "seed-host-4",
    hostName: "Ahmed Al Farsi",
    status: "approved",
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    country: "India",
    state: "Kerala",
    district: "Idukki",
    parentCategory: "Stays",
    category: "Farm Stays",
    subcategory: "Luxury Farm House",
    type: "farmstay",
    city: "Idukki",
    customFilters: [],
    advancedFilters: ["Swimming Pool", "BBQ Area"],
    photoUrls: [],
    photoCount: 0,
    featured: true,
    flaggedForReview: false,
    cancellationPolicyId: "flexible",
  },
  {
    id: "L-A02",
    title: "Spice Garden Cottage",
    description: "Cozy cottage with herb garden and farm-to-table dining.",
    hostId: "seed-host-5",
    hostName: "Sara Khan",
    status: "approved",
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    country: "India",
    state: "Kerala",
    district: "Kozhikode",
    parentCategory: "Stays",
    category: "Homestays",
    subcategory: "Family Homestay",
    type: "homestay",
    city: "Kozhikode",
    customFilters: [],
    advancedFilters: ["WiFi", "Family Friendly"],
    photoUrls: [],
    photoCount: 0,
    featured: false,
    flaggedForReview: true,
  },
];

const ALL_SEEDS = [...SEED_SUBMISSIONS, ...SEED_ACTIVE];


export function getSeedListings(): SubmittedListing[] {
  return ALL_SEEDS.map((l) => ({ ...l }));
}

export { ALL_SEEDS };
